version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=guessing_game_db
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./output.csv:/docker-entrypoint-initdb.d/output.csv
     # - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    ports:
      - "5432:5432"

  backend:
    build: ./backend/DACOMP_Guessr
    volumes:
      - ./backend/DACOMP_Guessr:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=guessing_game_db
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
      - DJANGO_SUPERUSER_PASSWORD=admin123

volumes:
  postgres_data_dev:
