# Generated by Django 5.2.11 on 2026-02-21 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('place_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(default='Norte', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('is_connected', models.BooleanField(default=True)),
                ('avatar_config', models.JSONField(default=dict)),
                ('score', models.FloatField(default=0.0)),
                ('last_round_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('total_rounds', models.IntegerField(default=5)),
                ('time_limit', models.IntegerField(default=60)),
                ('player_limit', models.IntegerField(default=10)),
                ('current_round_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('LOBBY', 'Aguardando'), ('PLAYING', 'Jogando'), ('FINISHED', 'Finalizado')], default='LOBBY', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_rounds', to='Guessing_Game.location')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='Guessing_Game.session')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('session', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_guess', models.FloatField()),
                ('longitude_guess', models.FloatField()),
                ('distance_in_meters', models.FloatField()),
                ('points_awarded', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='Guessing_Game.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='Guessing_Game.round')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='Guessing_Game.session'),
        ),
    ]
