# Generated by Django 5.2.12 on 2026-03-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guessing_Game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('INACTIVE', 'Inativa'), ('LOBBY', 'Aguardando'), ('PLAYING', 'Jogando'), ('FINISHED', 'Finalizado')], default='LOBBY', max_length=10),
        ),
    ]
