# Generated by Django 5.2.12 on 2026-03-09 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guessing_Game', '0002_alter_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='round_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
